### ISSUE TITLE
improve DBT-ID handling

### ISSUE THREAD

**Issue by kkrebs** [ThULB/ThUniBib#132]
Da der Verweis auf die lokale Kopie einer OA Veröffentlichung als wichtig angesehen wird, sollte das dafür vorhandene(!) Datenfeld auch mit der dbt-ID befüllt und entsprechend mit einem Link in die dbt versehen werden.

s.: https://thunibib-ilmenau.gbv.de/servlets/DozBibEntryServlet?id=ubo_mods_00056755

???ubo.identifier.dbt???: dbt_mods_00024549

Feldname = DBT ID
Anzeige: sollte identisch sein -> DBT ID
Die ID sollte wie folgt verlinkt werden: https://www.db-thueringen.de/receive/dbt_mods_00024549

**Comment by Possommi** [comment]
resolved with https://github.com/ThULB/ThUniBib/issues/210
