### ISSUE TITLE
Auswahlmenü der Verweise

### ISSUE THREAD

**Issue by Possommi** [ThULB/ThUniBib#140]
aktuell vorhanden: Referenziert, Vorgänger, Nachfolger, Ist Review von
	☐ bitte umbenennen: Ist Review von Rezension von
	☐ bitte neu ergänzen: Andere Version, Anderes Format

**Comment by kkrebs** [comment]
Kann identisch zu MIR umgesetzt werden?!
![grafik](https://user-images.githubusercontent.com/944083/179980316-f6b8ae6f-4048-407c-9195-fa23908da9ce.png)
