### ISSUE TITLE
[Ilmenau] automated classification mapping in pica2mods

### ISSUE THREAD

**Issue by kkrebs** [ThULB/ThUniBib#26]
Datenimport qualitativ hochwertiger Daten aus der vorhandenen TU-Hochschulbibliographie in das neue System und automatisierte Zuordnung von PICA-XML-Daten zu:
a. Unistruktur (Fakultät, etc.),
b. Destatis Klassifikation,
c. OA Informationen.

**Comment by Possommi** [comment]
resolved with https://github.com/ThULB/ThUniBib/pull/255
