### ISSUE TITLE
Configure editors by genre

### ISSUE THREAD

**Issue by Possommi** [ThULB/ThUniBib#52]

**Comment by kkrebs** [comment]
Hier mal eine Übersicht der Punkte die mir bei der Artikel-Erfassung aufgefallen sind:
- Reihenfolge der Felder noch nicht ganz wie in Vorgabe
- Fachgebiet soll Pflichtfeld sein
- Tags kommen ganz weg
- Ressourcentyp, Open Access, Datenträgertyp, Lizenztyp, PeerReview, Zweitveröffentlichung, Körperschaft, Umfang fehlt bei Gast-Nutzer-Erfassung
- Anmerkung fehlt
- Artikelnummer fehlt bei Zeitschriftenangaben

Rückmeldung an Team:
- Auswahl Dokumenttyp bei den einzelnen Erfassungsmasken nicht sinnvoll?!
- Soll Gast-/Einreichender-Nutzer Artikel etc. wirklich an bestehende Publikationen hängen dürfen? Das ist schwierig zu lösen, da dieser dann auch Schreibrechte dafür braucht ...
